(cl:in-package prx_simulation-msg)
(cl:export '(NODE_NAME-VAL
          NODE_NAME
          CONSUMER-VAL
          CONSUMER
          GOAL_RADIUS-VAL
          GOAL_RADIUS
          BOMB_RADIUS-VAL
          BOMB_RADIUS
          BOMB_FREQUENCY-VAL
          BOMB_FREQUENCY
          MY_BOMB_STATE-VAL
          MY_BOMB_STATE
          OPP_BOMB_STATE-VAL
          OPP_BOMB_STATE
          MY_GOAL-VAL
          MY_GOAL
          OPP_GOAL-VAL
          OPP_GOAL
          MY_POSITION-VAL
          MY_POSITION
          OPP_POSITION-VAL
          OPP_POSITION
          MY_RESPAWN-VAL
          MY_RESPAWN
          OPP_RESPAWN-VAL
          OPP_RESPAWN
          TIMESTAMP-VAL
          TIMESTAMP
          EXPLODED-VAL
          EXPLODED
          NEW_CONTINGENCY_USED-VAL
          NEW_CONTINGENCY_USED
          CONTINGENCY_LENGTH-VAL
          CONTINGENCY_LENGTH
))