"""autogenerated by genpy from prx_simulation/query_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import prx_simulation.msg

class query_msg(genpy.Message):
  _md5sum = "fb31a10de45da54e6e1d08424cc04ea2"
  _type = "prx_simulation/query_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string consumer
float64[] start
float64[] goal
float64 goal_region_radius
bool smooth_plan
bool set_goal_criterion
plant_locations_msg plant_locations
================================================================================
MSG: prx_simulation/plant_locations_msg
state_msg[] plant_states
string[] plant_paths
string node_name
================================================================================
MSG: prx_simulation/state_msg
float64[] elements
string node_name
string consumer_name
float64 timestamp
"""
  __slots__ = ['consumer','start','goal','goal_region_radius','smooth_plan','set_goal_criterion','plant_locations']
  _slot_types = ['string','float64[]','float64[]','float64','bool','bool','prx_simulation/plant_locations_msg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       consumer,start,goal,goal_region_radius,smooth_plan,set_goal_criterion,plant_locations

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(query_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.consumer is None:
        self.consumer = ''
      if self.start is None:
        self.start = []
      if self.goal is None:
        self.goal = []
      if self.goal_region_radius is None:
        self.goal_region_radius = 0.
      if self.smooth_plan is None:
        self.smooth_plan = False
      if self.set_goal_criterion is None:
        self.set_goal_criterion = False
      if self.plant_locations is None:
        self.plant_locations = prx_simulation.msg.plant_locations_msg()
    else:
      self.consumer = ''
      self.start = []
      self.goal = []
      self.goal_region_radius = 0.
      self.smooth_plan = False
      self.set_goal_criterion = False
      self.plant_locations = prx_simulation.msg.plant_locations_msg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.consumer
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.start)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.start))
      length = len(self.goal)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.goal))
      _x = self
      buff.write(_struct_d2B.pack(_x.goal_region_radius, _x.smooth_plan, _x.set_goal_criterion))
      length = len(self.plant_locations.plant_states)
      buff.write(_struct_I.pack(length))
      for val1 in self.plant_locations.plant_states:
        length = len(val1.elements)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.pack(pattern, *val1.elements))
        _x = val1.node_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.consumer_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_struct_d.pack(val1.timestamp))
      length = len(self.plant_locations.plant_paths)
      buff.write(_struct_I.pack(length))
      for val1 in self.plant_locations.plant_paths:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *val1))
        else:
          buff.write(struct.pack('<I%ss'%length, length, val1))
      _x = self.plant_locations.node_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.plant_locations is None:
        self.plant_locations = prx_simulation.msg.plant_locations_msg()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.consumer = str[start:end].decode('utf-8')
      else:
        self.consumer = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.start = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.goal = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 10
      (_x.goal_region_radius, _x.smooth_plan, _x.set_goal_criterion,) = _struct_d2B.unpack(str[start:end])
      self.smooth_plan = bool(self.smooth_plan)
      self.set_goal_criterion = bool(self.set_goal_criterion)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.plant_locations.plant_states = []
      for i in range(0, length):
        val1 = prx_simulation.msg.state_msg()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        end += struct.calcsize(pattern)
        val1.elements = struct.unpack(pattern, str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.node_name = str[start:end].decode('utf-8')
        else:
          val1.node_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.consumer_name = str[start:end].decode('utf-8')
        else:
          val1.consumer_name = str[start:end]
        start = end
        end += 8
        (val1.timestamp,) = _struct_d.unpack(str[start:end])
        self.plant_locations.plant_states.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.plant_locations.plant_paths = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.plant_locations.plant_paths.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.plant_locations.node_name = str[start:end].decode('utf-8')
      else:
        self.plant_locations.node_name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.consumer
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.start)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.start.tostring())
      length = len(self.goal)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.goal.tostring())
      _x = self
      buff.write(_struct_d2B.pack(_x.goal_region_radius, _x.smooth_plan, _x.set_goal_criterion))
      length = len(self.plant_locations.plant_states)
      buff.write(_struct_I.pack(length))
      for val1 in self.plant_locations.plant_states:
        length = len(val1.elements)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.elements.tostring())
        _x = val1.node_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.consumer_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *_x))
        else:
          buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_struct_d.pack(val1.timestamp))
      length = len(self.plant_locations.plant_paths)
      buff.write(_struct_I.pack(length))
      for val1 in self.plant_locations.plant_paths:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        if python3:
          buff.write(struct.pack('<I%sB'%length, length, *val1))
        else:
          buff.write(struct.pack('<I%ss'%length, length, val1))
      _x = self.plant_locations.node_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.plant_locations is None:
        self.plant_locations = prx_simulation.msg.plant_locations_msg()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.consumer = str[start:end].decode('utf-8')
      else:
        self.consumer = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.start = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.goal = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 10
      (_x.goal_region_radius, _x.smooth_plan, _x.set_goal_criterion,) = _struct_d2B.unpack(str[start:end])
      self.smooth_plan = bool(self.smooth_plan)
      self.set_goal_criterion = bool(self.set_goal_criterion)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.plant_locations.plant_states = []
      for i in range(0, length):
        val1 = prx_simulation.msg.state_msg()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        end += struct.calcsize(pattern)
        val1.elements = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.node_name = str[start:end].decode('utf-8')
        else:
          val1.node_name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.consumer_name = str[start:end].decode('utf-8')
        else:
          val1.consumer_name = str[start:end]
        start = end
        end += 8
        (val1.timestamp,) = _struct_d.unpack(str[start:end])
        self.plant_locations.plant_states.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.plant_locations.plant_paths = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.plant_locations.plant_paths.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.plant_locations.node_name = str[start:end].decode('utf-8')
      else:
        self.plant_locations.node_name = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_d2B = struct.Struct("<d2B")
_struct_d = struct.Struct("<d")
