// Generated by gencpp from file prx_utilities/create_HUD_srv.msg
// DO NOT EDIT!


#ifndef PRX_UTILITIES_MESSAGE_CREATE_HUD_SRV_H
#define PRX_UTILITIES_MESSAGE_CREATE_HUD_SRV_H

#include <ros/service_traits.h>


#include <prx_utilities/create_HUD_srvRequest.h>
#include <prx_utilities/create_HUD_srvResponse.h>


namespace prx_utilities
{

struct create_HUD_srv
{

typedef create_HUD_srvRequest Request;
typedef create_HUD_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct create_HUD_srv
} // namespace prx_utilities


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prx_utilities::create_HUD_srv > {
  static const char* value()
  {
    return "25298e7c8aa400f277cece434a3730ac";
  }

  static const char* value(const ::prx_utilities::create_HUD_srv&) { return value(); }
};

template<>
struct DataType< ::prx_utilities::create_HUD_srv > {
  static const char* value()
  {
    return "prx_utilities/create_HUD_srv";
  }

  static const char* value(const ::prx_utilities::create_HUD_srv&) { return value(); }
};


// service_traits::MD5Sum< ::prx_utilities::create_HUD_srvRequest> should match 
// service_traits::MD5Sum< ::prx_utilities::create_HUD_srv > 
template<>
struct MD5Sum< ::prx_utilities::create_HUD_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prx_utilities::create_HUD_srv >::value();
  }
  static const char* value(const ::prx_utilities::create_HUD_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prx_utilities::create_HUD_srvRequest> should match 
// service_traits::DataType< ::prx_utilities::create_HUD_srv > 
template<>
struct DataType< ::prx_utilities::create_HUD_srvRequest>
{
  static const char* value()
  {
    return DataType< ::prx_utilities::create_HUD_srv >::value();
  }
  static const char* value(const ::prx_utilities::create_HUD_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prx_utilities::create_HUD_srvResponse> should match 
// service_traits::MD5Sum< ::prx_utilities::create_HUD_srv > 
template<>
struct MD5Sum< ::prx_utilities::create_HUD_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prx_utilities::create_HUD_srv >::value();
  }
  static const char* value(const ::prx_utilities::create_HUD_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prx_utilities::create_HUD_srvResponse> should match 
// service_traits::DataType< ::prx_utilities::create_HUD_srv > 
template<>
struct DataType< ::prx_utilities::create_HUD_srvResponse>
{
  static const char* value()
  {
    return DataType< ::prx_utilities::create_HUD_srv >::value();
  }
  static const char* value(const ::prx_utilities::create_HUD_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRX_UTILITIES_MESSAGE_CREATE_HUD_SRV_H
