// Generated by gencpp from file prx_utilities/query_planner_srv.msg
// DO NOT EDIT!


#ifndef PRX_UTILITIES_MESSAGE_QUERY_PLANNER_SRV_H
#define PRX_UTILITIES_MESSAGE_QUERY_PLANNER_SRV_H

#include <ros/service_traits.h>


#include <prx_utilities/query_planner_srvRequest.h>
#include <prx_utilities/query_planner_srvResponse.h>


namespace prx_utilities
{

struct query_planner_srv
{

typedef query_planner_srvRequest Request;
typedef query_planner_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct query_planner_srv
} // namespace prx_utilities


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prx_utilities::query_planner_srv > {
  static const char* value()
  {
    return "2b33061955e07f2075794f74beed8286";
  }

  static const char* value(const ::prx_utilities::query_planner_srv&) { return value(); }
};

template<>
struct DataType< ::prx_utilities::query_planner_srv > {
  static const char* value()
  {
    return "prx_utilities/query_planner_srv";
  }

  static const char* value(const ::prx_utilities::query_planner_srv&) { return value(); }
};


// service_traits::MD5Sum< ::prx_utilities::query_planner_srvRequest> should match 
// service_traits::MD5Sum< ::prx_utilities::query_planner_srv > 
template<>
struct MD5Sum< ::prx_utilities::query_planner_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prx_utilities::query_planner_srv >::value();
  }
  static const char* value(const ::prx_utilities::query_planner_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prx_utilities::query_planner_srvRequest> should match 
// service_traits::DataType< ::prx_utilities::query_planner_srv > 
template<>
struct DataType< ::prx_utilities::query_planner_srvRequest>
{
  static const char* value()
  {
    return DataType< ::prx_utilities::query_planner_srv >::value();
  }
  static const char* value(const ::prx_utilities::query_planner_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prx_utilities::query_planner_srvResponse> should match 
// service_traits::MD5Sum< ::prx_utilities::query_planner_srv > 
template<>
struct MD5Sum< ::prx_utilities::query_planner_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prx_utilities::query_planner_srv >::value();
  }
  static const char* value(const ::prx_utilities::query_planner_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prx_utilities::query_planner_srvResponse> should match 
// service_traits::DataType< ::prx_utilities::query_planner_srv > 
template<>
struct DataType< ::prx_utilities::query_planner_srvResponse>
{
  static const char* value()
  {
    return DataType< ::prx_utilities::query_planner_srv >::value();
  }
  static const char* value(const ::prx_utilities::query_planner_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRX_UTILITIES_MESSAGE_QUERY_PLANNER_SRV_H
