// Generated by gencpp from file prx_utilities/rigid_body_info_msg.msg
// DO NOT EDIT!


#ifndef PRX_UTILITIES_MESSAGE_RIGID_BODY_INFO_MSG_H
#define PRX_UTILITIES_MESSAGE_RIGID_BODY_INFO_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prx_utilities
{
template <class ContainerAllocator>
struct rigid_body_info_msg_
{
  typedef rigid_body_info_msg_<ContainerAllocator> Type;

  rigid_body_info_msg_()
    : system_name()
    , rigid_body_name()
    , material_name()
    , geometry_type(0)
    , geometry_params()
    , color_rgba()  {
    }
  rigid_body_info_msg_(const ContainerAllocator& _alloc)
    : system_name(_alloc)
    , rigid_body_name(_alloc)
    , material_name(_alloc)
    , geometry_type(0)
    , geometry_params(_alloc)
    , color_rgba(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _system_name_type;
  _system_name_type system_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _rigid_body_name_type;
  _rigid_body_name_type rigid_body_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _material_name_type;
  _material_name_type material_name;

   typedef uint8_t _geometry_type_type;
  _geometry_type_type geometry_type;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _geometry_params_type;
  _geometry_params_type geometry_params;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _color_rgba_type;
  _color_rgba_type color_rgba;


    enum { SPHERE = 1u };
     enum { BOX = 2u };
     enum { CONE = 3u };
     enum { CYLINDER = 4u };
     enum { OPEN_CYLINDER = 5u };
     enum { CAPSULE = 6u };
     enum { TRIANGLE = 7u };
     enum { QUAD = 8u };
     enum { LINES = 9u };
     enum { LINESTRIP = 10u };
     enum { MESH = 11u };
 

  typedef boost::shared_ptr< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> const> ConstPtr;

}; // struct rigid_body_info_msg_

typedef ::prx_utilities::rigid_body_info_msg_<std::allocator<void> > rigid_body_info_msg;

typedef boost::shared_ptr< ::prx_utilities::rigid_body_info_msg > rigid_body_info_msgPtr;
typedef boost::shared_ptr< ::prx_utilities::rigid_body_info_msg const> rigid_body_info_msgConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_utilities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'prx_utilities': ['/home/parallels/Desktop/ROS_workspace/src/prx_utilities/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d3e185885c45ca9d656997df5a70642";
  }

  static const char* value(const ::prx_utilities::rigid_body_info_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d3e185885c45ca9ULL;
  static const uint64_t static_value2 = 0xd656997df5a70642ULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_utilities/rigid_body_info_msg";
  }

  static const char* value(const ::prx_utilities::rigid_body_info_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 SPHERE=1\n\
uint8 BOX=2\n\
uint8 CONE=3\n\
uint8 CYLINDER=4\n\
uint8 OPEN_CYLINDER=5\n\
uint8 CAPSULE=6\n\
uint8 TRIANGLE=7\n\
uint8 QUAD=8\n\
uint8 LINES=9\n\
uint8 LINESTRIP=10\n\
uint8 MESH=11\n\
\n\
string system_name\n\
string rigid_body_name\n\
string material_name\n\
uint8 geometry_type\n\
float64[] geometry_params\n\
float64[] color_rgba\n\
";
  }

  static const char* value(const ::prx_utilities::rigid_body_info_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.system_name);
      stream.next(m.rigid_body_name);
      stream.next(m.material_name);
      stream.next(m.geometry_type);
      stream.next(m.geometry_params);
      stream.next(m.color_rgba);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct rigid_body_info_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_utilities::rigid_body_info_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_utilities::rigid_body_info_msg_<ContainerAllocator>& v)
  {
    s << indent << "system_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.system_name);
    s << indent << "rigid_body_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.rigid_body_name);
    s << indent << "material_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.material_name);
    s << indent << "geometry_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.geometry_type);
    s << indent << "geometry_params[]" << std::endl;
    for (size_t i = 0; i < v.geometry_params.size(); ++i)
    {
      s << indent << "  geometry_params[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.geometry_params[i]);
    }
    s << indent << "color_rgba[]" << std::endl;
    for (size_t i = 0; i < v.color_rgba.size(); ++i)
    {
      s << indent << "  color_rgba[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.color_rgba[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_UTILITIES_MESSAGE_RIGID_BODY_INFO_MSG_H
