// Generated by gencpp from file prx_utilities/scene_text_msg.msg
// DO NOT EDIT!


#ifndef PRX_UTILITIES_MESSAGE_SCENE_TEXT_MSG_H
#define PRX_UTILITIES_MESSAGE_SCENE_TEXT_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prx_utilities
{
template <class ContainerAllocator>
struct scene_text_msg_
{
  typedef scene_text_msg_<ContainerAllocator> Type;

  scene_text_msg_()
    : anchored_system()
    , text()
    , text_name()
    , relative_position()
    , color_rgba()
    , font_size(0.0)
    , font()  {
    }
  scene_text_msg_(const ContainerAllocator& _alloc)
    : anchored_system(_alloc)
    , text(_alloc)
    , text_name(_alloc)
    , relative_position(_alloc)
    , color_rgba(_alloc)
    , font_size(0.0)
    , font(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _anchored_system_type;
  _anchored_system_type anchored_system;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_name_type;
  _text_name_type text_name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _relative_position_type;
  _relative_position_type relative_position;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _color_rgba_type;
  _color_rgba_type color_rgba;

   typedef double _font_size_type;
  _font_size_type font_size;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _font_type;
  _font_type font;




  typedef boost::shared_ptr< ::prx_utilities::scene_text_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_utilities::scene_text_msg_<ContainerAllocator> const> ConstPtr;

}; // struct scene_text_msg_

typedef ::prx_utilities::scene_text_msg_<std::allocator<void> > scene_text_msg;

typedef boost::shared_ptr< ::prx_utilities::scene_text_msg > scene_text_msgPtr;
typedef boost::shared_ptr< ::prx_utilities::scene_text_msg const> scene_text_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_utilities::scene_text_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_utilities::scene_text_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_utilities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'prx_utilities': ['/home/parallels/Desktop/ROS_workspace/src/prx_utilities/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::scene_text_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::scene_text_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::scene_text_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::scene_text_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::scene_text_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::scene_text_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_utilities::scene_text_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d98e38b3d1e2b92206c61f0e733d8f9";
  }

  static const char* value(const ::prx_utilities::scene_text_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d98e38b3d1e2b92ULL;
  static const uint64_t static_value2 = 0x206c61f0e733d8f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_utilities::scene_text_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_utilities/scene_text_msg";
  }

  static const char* value(const ::prx_utilities::scene_text_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_utilities::scene_text_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string anchored_system\n\
string text\n\
string text_name\n\
float64[] relative_position\n\
float64[] color_rgba\n\
float64 font_size\n\
string font\n\
";
  }

  static const char* value(const ::prx_utilities::scene_text_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_utilities::scene_text_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.anchored_system);
      stream.next(m.text);
      stream.next(m.text_name);
      stream.next(m.relative_position);
      stream.next(m.color_rgba);
      stream.next(m.font_size);
      stream.next(m.font);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct scene_text_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_utilities::scene_text_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_utilities::scene_text_msg_<ContainerAllocator>& v)
  {
    s << indent << "anchored_system: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.anchored_system);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
    s << indent << "text_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text_name);
    s << indent << "relative_position[]" << std::endl;
    for (size_t i = 0; i < v.relative_position.size(); ++i)
    {
      s << indent << "  relative_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.relative_position[i]);
    }
    s << indent << "color_rgba[]" << std::endl;
    for (size_t i = 0; i < v.color_rgba.size(); ++i)
    {
      s << indent << "  color_rgba[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.color_rgba[i]);
    }
    s << indent << "font_size: ";
    Printer<double>::stream(s, indent + "  ", v.font_size);
    s << indent << "font: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.font);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_UTILITIES_MESSAGE_SCENE_TEXT_MSG_H
