// Generated by gencpp from file prx_utilities/shutdown_node_srvRequest.msg
// DO NOT EDIT!


#ifndef PRX_UTILITIES_MESSAGE_SHUTDOWN_NODE_SRVREQUEST_H
#define PRX_UTILITIES_MESSAGE_SHUTDOWN_NODE_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prx_utilities
{
template <class ContainerAllocator>
struct shutdown_node_srvRequest_
{
  typedef shutdown_node_srvRequest_<ContainerAllocator> Type;

  shutdown_node_srvRequest_()
    : destination_node_name()
    , source_node_name()  {
    }
  shutdown_node_srvRequest_(const ContainerAllocator& _alloc)
    : destination_node_name(_alloc)
    , source_node_name(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _destination_node_name_type;
  _destination_node_name_type destination_node_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _source_node_name_type;
  _source_node_name_type source_node_name;




  typedef boost::shared_ptr< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct shutdown_node_srvRequest_

typedef ::prx_utilities::shutdown_node_srvRequest_<std::allocator<void> > shutdown_node_srvRequest;

typedef boost::shared_ptr< ::prx_utilities::shutdown_node_srvRequest > shutdown_node_srvRequestPtr;
typedef boost::shared_ptr< ::prx_utilities::shutdown_node_srvRequest const> shutdown_node_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_utilities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'prx_utilities': ['/home/parallels/Desktop/ROS_workspace/src/prx_utilities/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b261e5b15df599b49cbecb3c73fa812";
  }

  static const char* value(const ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b261e5b15df599bULL;
  static const uint64_t static_value2 = 0x49cbecb3c73fa812ULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_utilities/shutdown_node_srvRequest";
  }

  static const char* value(const ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string destination_node_name\n\
string source_node_name\n\
";
  }

  static const char* value(const ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination_node_name);
      stream.next(m.source_node_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct shutdown_node_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_utilities::shutdown_node_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "destination_node_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.destination_node_name);
    s << indent << "source_node_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.source_node_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_UTILITIES_MESSAGE_SHUTDOWN_NODE_SRVREQUEST_H
