// Generated by gencpp from file prx_utilities/space_msg.msg
// DO NOT EDIT!


#ifndef PRX_UTILITIES_MESSAGE_SPACE_MSG_H
#define PRX_UTILITIES_MESSAGE_SPACE_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prx_utilities
{
template <class ContainerAllocator>
struct space_msg_
{
  typedef space_msg_<ContainerAllocator> Type;

  space_msg_()
    : system_path()
    , dimension()  {
    }
  space_msg_(const ContainerAllocator& _alloc)
    : system_path(_alloc)
    , dimension(_alloc)  {
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _system_path_type;
  _system_path_type system_path;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _dimension_type;
  _dimension_type dimension;




  typedef boost::shared_ptr< ::prx_utilities::space_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_utilities::space_msg_<ContainerAllocator> const> ConstPtr;

}; // struct space_msg_

typedef ::prx_utilities::space_msg_<std::allocator<void> > space_msg;

typedef boost::shared_ptr< ::prx_utilities::space_msg > space_msgPtr;
typedef boost::shared_ptr< ::prx_utilities::space_msg const> space_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_utilities::space_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_utilities::space_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_utilities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'prx_utilities': ['/home/parallels/Desktop/ROS_workspace/src/prx_utilities/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::space_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::space_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::space_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::space_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::space_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::space_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_utilities::space_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "220c2fd8cce8ce4e664c7510ec880b0e";
  }

  static const char* value(const ::prx_utilities::space_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x220c2fd8cce8ce4eULL;
  static const uint64_t static_value2 = 0x664c7510ec880b0eULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_utilities::space_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_utilities/space_msg";
  }

  static const char* value(const ::prx_utilities::space_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_utilities::space_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] system_path\n\
uint8[] dimension\n\
";
  }

  static const char* value(const ::prx_utilities::space_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_utilities::space_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.system_path);
      stream.next(m.dimension);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct space_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_utilities::space_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_utilities::space_msg_<ContainerAllocator>& v)
  {
    s << indent << "system_path[]" << std::endl;
    for (size_t i = 0; i < v.system_path.size(); ++i)
    {
      s << indent << "  system_path[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.system_path[i]);
    }
    s << indent << "dimension[]" << std::endl;
    for (size_t i = 0; i < v.dimension.size(); ++i)
    {
      s << indent << "  dimension[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.dimension[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_UTILITIES_MESSAGE_SPACE_MSG_H
