// Generated by gencpp from file prx_utilities/update_twoD_text_srvRequest.msg
// DO NOT EDIT!


#ifndef PRX_UTILITIES_MESSAGE_UPDATE_TWOD_TEXT_SRVREQUEST_H
#define PRX_UTILITIES_MESSAGE_UPDATE_TWOD_TEXT_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prx_utilities
{
template <class ContainerAllocator>
struct update_twoD_text_srvRequest_
{
  typedef update_twoD_text_srvRequest_<ContainerAllocator> Type;

  update_twoD_text_srvRequest_()
    : our_name()
    , text()
    , relative_position()
    , color()
    , delete_text(0)  {
    }
  update_twoD_text_srvRequest_(const ContainerAllocator& _alloc)
    : our_name(_alloc)
    , text(_alloc)
    , relative_position(_alloc)
    , color(_alloc)
    , delete_text(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _our_name_type;
  _our_name_type our_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _relative_position_type;
  _relative_position_type relative_position;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _color_type;
  _color_type color;

   typedef uint16_t _delete_text_type;
  _delete_text_type delete_text;




  typedef boost::shared_ptr< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct update_twoD_text_srvRequest_

typedef ::prx_utilities::update_twoD_text_srvRequest_<std::allocator<void> > update_twoD_text_srvRequest;

typedef boost::shared_ptr< ::prx_utilities::update_twoD_text_srvRequest > update_twoD_text_srvRequestPtr;
typedef boost::shared_ptr< ::prx_utilities::update_twoD_text_srvRequest const> update_twoD_text_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_utilities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'prx_utilities': ['/home/parallels/Desktop/ROS_workspace/src/prx_utilities/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54549bddf7184557b99998def9d1baef";
  }

  static const char* value(const ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54549bddf7184557ULL;
  static const uint64_t static_value2 = 0xb99998def9d1baefULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_utilities/update_twoD_text_srvRequest";
  }

  static const char* value(const ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string our_name\n\
string text\n\
float64[] relative_position\n\
float64[] color\n\
uint16 delete_text\n\
";
  }

  static const char* value(const ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.our_name);
      stream.next(m.text);
      stream.next(m.relative_position);
      stream.next(m.color);
      stream.next(m.delete_text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct update_twoD_text_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_utilities::update_twoD_text_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "our_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.our_name);
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
    s << indent << "relative_position[]" << std::endl;
    for (size_t i = 0; i < v.relative_position.size(); ++i)
    {
      s << indent << "  relative_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.relative_position[i]);
    }
    s << indent << "color[]" << std::endl;
    for (size_t i = 0; i < v.color.size(); ++i)
    {
      s << indent << "  color[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.color[i]);
    }
    s << indent << "delete_text: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.delete_text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_UTILITIES_MESSAGE_UPDATE_TWOD_TEXT_SRVREQUEST_H
