// Generated by gencpp from file prx_utilities/Vec4_msg.msg
// DO NOT EDIT!


#ifndef PRX_UTILITIES_MESSAGE_VEC4_MSG_H
#define PRX_UTILITIES_MESSAGE_VEC4_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prx_utilities
{
template <class ContainerAllocator>
struct Vec4_msg_
{
  typedef Vec4_msg_<ContainerAllocator> Type;

  Vec4_msg_()
    : r(0.0)
    , g(0.0)
    , b(0.0)
    , a(0.0)  {
    }
  Vec4_msg_(const ContainerAllocator& _alloc)
    : r(0.0)
    , g(0.0)
    , b(0.0)
    , a(0.0)  {
    }



   typedef double _r_type;
  _r_type r;

   typedef double _g_type;
  _g_type g;

   typedef double _b_type;
  _b_type b;

   typedef double _a_type;
  _a_type a;




  typedef boost::shared_ptr< ::prx_utilities::Vec4_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_utilities::Vec4_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Vec4_msg_

typedef ::prx_utilities::Vec4_msg_<std::allocator<void> > Vec4_msg;

typedef boost::shared_ptr< ::prx_utilities::Vec4_msg > Vec4_msgPtr;
typedef boost::shared_ptr< ::prx_utilities::Vec4_msg const> Vec4_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_utilities::Vec4_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_utilities::Vec4_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_utilities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'prx_utilities': ['/home/parallels/Desktop/ROS_workspace/src/prx_utilities/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::Vec4_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::Vec4_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::Vec4_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::Vec4_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::Vec4_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::Vec4_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_utilities::Vec4_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b33e438d87f78a3ce37c50c7be85f344";
  }

  static const char* value(const ::prx_utilities::Vec4_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb33e438d87f78a3cULL;
  static const uint64_t static_value2 = 0xe37c50c7be85f344ULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_utilities::Vec4_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_utilities/Vec4_msg";
  }

  static const char* value(const ::prx_utilities::Vec4_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_utilities::Vec4_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 r\n\
float64 g\n\
float64 b\n\
float64 a\n\
";
  }

  static const char* value(const ::prx_utilities::Vec4_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_utilities::Vec4_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Vec4_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_utilities::Vec4_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_utilities::Vec4_msg_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<double>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_UTILITIES_MESSAGE_VEC4_MSG_H
