// Generated by gencpp from file prx_utilities/visualize_obstacles_srv.msg
// DO NOT EDIT!


#ifndef PRX_UTILITIES_MESSAGE_VISUALIZE_OBSTACLES_SRV_H
#define PRX_UTILITIES_MESSAGE_VISUALIZE_OBSTACLES_SRV_H

#include <ros/service_traits.h>


#include <prx_utilities/visualize_obstacles_srvRequest.h>
#include <prx_utilities/visualize_obstacles_srvResponse.h>


namespace prx_utilities
{

struct visualize_obstacles_srv
{

typedef visualize_obstacles_srvRequest Request;
typedef visualize_obstacles_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visualize_obstacles_srv
} // namespace prx_utilities


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prx_utilities::visualize_obstacles_srv > {
  static const char* value()
  {
    return "9981a66aae205a31636ef37b6da7095e";
  }

  static const char* value(const ::prx_utilities::visualize_obstacles_srv&) { return value(); }
};

template<>
struct DataType< ::prx_utilities::visualize_obstacles_srv > {
  static const char* value()
  {
    return "prx_utilities/visualize_obstacles_srv";
  }

  static const char* value(const ::prx_utilities::visualize_obstacles_srv&) { return value(); }
};


// service_traits::MD5Sum< ::prx_utilities::visualize_obstacles_srvRequest> should match 
// service_traits::MD5Sum< ::prx_utilities::visualize_obstacles_srv > 
template<>
struct MD5Sum< ::prx_utilities::visualize_obstacles_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prx_utilities::visualize_obstacles_srv >::value();
  }
  static const char* value(const ::prx_utilities::visualize_obstacles_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prx_utilities::visualize_obstacles_srvRequest> should match 
// service_traits::DataType< ::prx_utilities::visualize_obstacles_srv > 
template<>
struct DataType< ::prx_utilities::visualize_obstacles_srvRequest>
{
  static const char* value()
  {
    return DataType< ::prx_utilities::visualize_obstacles_srv >::value();
  }
  static const char* value(const ::prx_utilities::visualize_obstacles_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prx_utilities::visualize_obstacles_srvResponse> should match 
// service_traits::MD5Sum< ::prx_utilities::visualize_obstacles_srv > 
template<>
struct MD5Sum< ::prx_utilities::visualize_obstacles_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prx_utilities::visualize_obstacles_srv >::value();
  }
  static const char* value(const ::prx_utilities::visualize_obstacles_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prx_utilities::visualize_obstacles_srvResponse> should match 
// service_traits::DataType< ::prx_utilities::visualize_obstacles_srv > 
template<>
struct DataType< ::prx_utilities::visualize_obstacles_srvResponse>
{
  static const char* value()
  {
    return DataType< ::prx_utilities::visualize_obstacles_srv >::value();
  }
  static const char* value(const ::prx_utilities::visualize_obstacles_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRX_UTILITIES_MESSAGE_VISUALIZE_OBSTACLES_SRV_H
