// Generated by gencpp from file prx_utilities/visualize_ghost_plants_srvRequest.msg
// DO NOT EDIT!


#ifndef PRX_UTILITIES_MESSAGE_VISUALIZE_GHOST_PLANTS_SRVREQUEST_H
#define PRX_UTILITIES_MESSAGE_VISUALIZE_GHOST_PLANTS_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace prx_utilities
{
template <class ContainerAllocator>
struct visualize_ghost_plants_srvRequest_
{
  typedef visualize_ghost_plants_srvRequest_<ContainerAllocator> Type;

  visualize_ghost_plants_srvRequest_()
    : plant_paths()
    , ghost_configs()  {
    }
  visualize_ghost_plants_srvRequest_(const ContainerAllocator& _alloc)
    : plant_paths(_alloc)
    , ghost_configs(_alloc)  {
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _plant_paths_type;
  _plant_paths_type plant_paths;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _ghost_configs_type;
  _ghost_configs_type ghost_configs;




  typedef boost::shared_ptr< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct visualize_ghost_plants_srvRequest_

typedef ::prx_utilities::visualize_ghost_plants_srvRequest_<std::allocator<void> > visualize_ghost_plants_srvRequest;

typedef boost::shared_ptr< ::prx_utilities::visualize_ghost_plants_srvRequest > visualize_ghost_plants_srvRequestPtr;
typedef boost::shared_ptr< ::prx_utilities::visualize_ghost_plants_srvRequest const> visualize_ghost_plants_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_utilities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'prx_utilities': ['/home/parallels/Desktop/ROS_workspace/src/prx_utilities/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c1d97362737c2f9457429d28485d6b1";
  }

  static const char* value(const ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c1d97362737c2f9ULL;
  static const uint64_t static_value2 = 0x457429d28485d6b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_utilities/visualize_ghost_plants_srvRequest";
  }

  static const char* value(const ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] plant_paths\n\
geometry_msgs/Pose[] ghost_configs\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plant_paths);
      stream.next(m.ghost_configs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct visualize_ghost_plants_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_utilities::visualize_ghost_plants_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "plant_paths[]" << std::endl;
    for (size_t i = 0; i < v.plant_paths.size(); ++i)
    {
      s << indent << "  plant_paths[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.plant_paths[i]);
    }
    s << indent << "ghost_configs[]" << std::endl;
    for (size_t i = 0; i < v.ghost_configs.size(); ++i)
    {
      s << indent << "  ghost_configs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.ghost_configs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_UTILITIES_MESSAGE_VISUALIZE_GHOST_PLANTS_SRVREQUEST_H
