building1:
    type: obstacle
    geometries:
      -
        name: box1
        collision_geometry: 
          type: box
          dims: [200, 7, 4]      
          material: black       
        config:
          position: [-125, 0, 2]
          orientation: [0, 0, 0, 1]
      -
        name: box2
        collision_geometry: 
          type: box
          dims: [200, 7, 4]       
          material: black       
        config:
          position: [125, 0, 1]
          orientation: [0, 0, 0, 1]
    