building1:
    type: obstacle
    geometries:
      -
        name: box1
        collision_geometry: 
          type: box
          dims: [150, 350, 4]       
          material: black       
        config:
          position: [200, -100, 0]
          orientation: [0, 0, 0, 1]
      -
        name: box2
        collision_geometry: 
          type: box
          dims: [300, 100, 1]       
          material: black       
        config:
          position: [-200, 0, 0]
          orientation: [0, 0, 0, 1]
      -
        name: box3
        collision_geometry: 
          type: box
          dims: [105, 100, 1]       
          material: black       
        config:
          position: [120, 200, 0]
          orientation: [0, 0, 0, 1]
    