// Generated by gencpp from file prx_simulation/plant_locations_msg.msg
// DO NOT EDIT!


#ifndef PRX_SIMULATION_MESSAGE_PLANT_LOCATIONS_MSG_H
#define PRX_SIMULATION_MESSAGE_PLANT_LOCATIONS_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <prx_simulation/state_msg.h>

namespace prx_simulation
{
template <class ContainerAllocator>
struct plant_locations_msg_
{
  typedef plant_locations_msg_<ContainerAllocator> Type;

  plant_locations_msg_()
    : plant_states()
    , plant_paths()
    , node_name()  {
    }
  plant_locations_msg_(const ContainerAllocator& _alloc)
    : plant_states(_alloc)
    , plant_paths(_alloc)
    , node_name(_alloc)  {
    }



   typedef std::vector< ::prx_simulation::state_msg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::prx_simulation::state_msg_<ContainerAllocator> >::other >  _plant_states_type;
  _plant_states_type plant_states;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _plant_paths_type;
  _plant_paths_type plant_paths;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _node_name_type;
  _node_name_type node_name;




  typedef boost::shared_ptr< ::prx_simulation::plant_locations_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_simulation::plant_locations_msg_<ContainerAllocator> const> ConstPtr;

}; // struct plant_locations_msg_

typedef ::prx_simulation::plant_locations_msg_<std::allocator<void> > plant_locations_msg;

typedef boost::shared_ptr< ::prx_simulation::plant_locations_msg > plant_locations_msgPtr;
typedef boost::shared_ptr< ::prx_simulation::plant_locations_msg const> plant_locations_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_simulation::plant_locations_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_simulation::plant_locations_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_simulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'prx_simulation': ['/home/parallels/Desktop/ROS_workspace/src/prx_simulation/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_simulation::plant_locations_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_simulation::plant_locations_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_simulation::plant_locations_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_simulation::plant_locations_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_simulation::plant_locations_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_simulation::plant_locations_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_simulation::plant_locations_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecf23f5bb28cd312a2dba6ce7fc3b0ce";
  }

  static const char* value(const ::prx_simulation::plant_locations_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xecf23f5bb28cd312ULL;
  static const uint64_t static_value2 = 0xa2dba6ce7fc3b0ceULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_simulation::plant_locations_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_simulation/plant_locations_msg";
  }

  static const char* value(const ::prx_simulation::plant_locations_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_simulation::plant_locations_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_msg[] plant_states\n\
string[] plant_paths\n\
string node_name\n\
================================================================================\n\
MSG: prx_simulation/state_msg\n\
float64[] elements\n\
string node_name\n\
string consumer_name\n\
float64 timestamp\n\
";
  }

  static const char* value(const ::prx_simulation::plant_locations_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_simulation::plant_locations_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plant_states);
      stream.next(m.plant_paths);
      stream.next(m.node_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct plant_locations_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_simulation::plant_locations_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_simulation::plant_locations_msg_<ContainerAllocator>& v)
  {
    s << indent << "plant_states[]" << std::endl;
    for (size_t i = 0; i < v.plant_states.size(); ++i)
    {
      s << indent << "  plant_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::prx_simulation::state_msg_<ContainerAllocator> >::stream(s, indent + "    ", v.plant_states[i]);
    }
    s << indent << "plant_paths[]" << std::endl;
    for (size_t i = 0; i < v.plant_paths.size(); ++i)
    {
      s << indent << "  plant_paths[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.plant_paths[i]);
    }
    s << indent << "node_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.node_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_SIMULATION_MESSAGE_PLANT_LOCATIONS_MSG_H
