// Generated by gencpp from file prx_simulation/request_ground_truth_srvRequest.msg
// DO NOT EDIT!


#ifndef PRX_SIMULATION_MESSAGE_REQUEST_GROUND_TRUTH_SRVREQUEST_H
#define PRX_SIMULATION_MESSAGE_REQUEST_GROUND_TRUTH_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prx_simulation
{
template <class ContainerAllocator>
struct request_ground_truth_srvRequest_
{
  typedef request_ground_truth_srvRequest_<ContainerAllocator> Type;

  request_ground_truth_srvRequest_()
    : timestamp_request(0.0)
    , node_name()  {
    }
  request_ground_truth_srvRequest_(const ContainerAllocator& _alloc)
    : timestamp_request(0.0)
    , node_name(_alloc)  {
    }



   typedef double _timestamp_request_type;
  _timestamp_request_type timestamp_request;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _node_name_type;
  _node_name_type node_name;




  typedef boost::shared_ptr< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct request_ground_truth_srvRequest_

typedef ::prx_simulation::request_ground_truth_srvRequest_<std::allocator<void> > request_ground_truth_srvRequest;

typedef boost::shared_ptr< ::prx_simulation::request_ground_truth_srvRequest > request_ground_truth_srvRequestPtr;
typedef boost::shared_ptr< ::prx_simulation::request_ground_truth_srvRequest const> request_ground_truth_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_simulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'prx_simulation': ['/home/parallels/Desktop/ROS_workspace/src/prx_simulation/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90956c8a9d3ec220b03ff5bfba854f58";
  }

  static const char* value(const ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90956c8a9d3ec220ULL;
  static const uint64_t static_value2 = 0xb03ff5bfba854f58ULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_simulation/request_ground_truth_srvRequest";
  }

  static const char* value(const ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 timestamp_request\n\
string node_name\n\
";
  }

  static const char* value(const ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp_request);
      stream.next(m.node_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct request_ground_truth_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_simulation::request_ground_truth_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "timestamp_request: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp_request);
    s << indent << "node_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.node_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_SIMULATION_MESSAGE_REQUEST_GROUND_TRUTH_SRVREQUEST_H
