// Generated by gencpp from file prx_simulation/send_plans_srvRequest.msg
// DO NOT EDIT!


#ifndef PRX_SIMULATION_MESSAGE_SEND_PLANS_SRVREQUEST_H
#define PRX_SIMULATION_MESSAGE_SEND_PLANS_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <prx_simulation/control_msg.h>

namespace prx_simulation
{
template <class ContainerAllocator>
struct send_plans_srvRequest_
{
  typedef send_plans_srvRequest_<ContainerAllocator> Type;

  send_plans_srvRequest_()
    : plan()
    , system_name()  {
    }
  send_plans_srvRequest_(const ContainerAllocator& _alloc)
    : plan(_alloc)
    , system_name(_alloc)  {
    }



   typedef std::vector< ::prx_simulation::control_msg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::prx_simulation::control_msg_<ContainerAllocator> >::other >  _plan_type;
  _plan_type plan;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _system_name_type;
  _system_name_type system_name;




  typedef boost::shared_ptr< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct send_plans_srvRequest_

typedef ::prx_simulation::send_plans_srvRequest_<std::allocator<void> > send_plans_srvRequest;

typedef boost::shared_ptr< ::prx_simulation::send_plans_srvRequest > send_plans_srvRequestPtr;
typedef boost::shared_ptr< ::prx_simulation::send_plans_srvRequest const> send_plans_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_simulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'prx_simulation': ['/home/parallels/Desktop/ROS_workspace/src/prx_simulation/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ade7478e66fa27a6796727ef4a8e17a6";
  }

  static const char* value(const ::prx_simulation::send_plans_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xade7478e66fa27a6ULL;
  static const uint64_t static_value2 = 0x796727ef4a8e17a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_simulation/send_plans_srvRequest";
  }

  static const char* value(const ::prx_simulation::send_plans_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_simulation/control_msg[] plan\n\
string system_name\n\
\n\
================================================================================\n\
MSG: prx_simulation/control_msg\n\
float64[] control\n\
float64 duration\n\
";
  }

  static const char* value(const ::prx_simulation::send_plans_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan);
      stream.next(m.system_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct send_plans_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_simulation::send_plans_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_simulation::send_plans_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "plan[]" << std::endl;
    for (size_t i = 0; i < v.plan.size(); ++i)
    {
      s << indent << "  plan[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::prx_simulation::control_msg_<ContainerAllocator> >::stream(s, indent + "    ", v.plan[i]);
    }
    s << indent << "system_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.system_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_SIMULATION_MESSAGE_SEND_PLANS_SRVREQUEST_H
