// Generated by gencpp from file prx_simulation/send_plans_srv.msg
// DO NOT EDIT!


#ifndef PRX_SIMULATION_MESSAGE_SEND_PLANS_SRV_H
#define PRX_SIMULATION_MESSAGE_SEND_PLANS_SRV_H

#include <ros/service_traits.h>


#include <prx_simulation/send_plans_srvRequest.h>
#include <prx_simulation/send_plans_srvResponse.h>


namespace prx_simulation
{

struct send_plans_srv
{

typedef send_plans_srvRequest Request;
typedef send_plans_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct send_plans_srv
} // namespace prx_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prx_simulation::send_plans_srv > {
  static const char* value()
  {
    return "ade7478e66fa27a6796727ef4a8e17a6";
  }

  static const char* value(const ::prx_simulation::send_plans_srv&) { return value(); }
};

template<>
struct DataType< ::prx_simulation::send_plans_srv > {
  static const char* value()
  {
    return "prx_simulation/send_plans_srv";
  }

  static const char* value(const ::prx_simulation::send_plans_srv&) { return value(); }
};


// service_traits::MD5Sum< ::prx_simulation::send_plans_srvRequest> should match 
// service_traits::MD5Sum< ::prx_simulation::send_plans_srv > 
template<>
struct MD5Sum< ::prx_simulation::send_plans_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prx_simulation::send_plans_srv >::value();
  }
  static const char* value(const ::prx_simulation::send_plans_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prx_simulation::send_plans_srvRequest> should match 
// service_traits::DataType< ::prx_simulation::send_plans_srv > 
template<>
struct DataType< ::prx_simulation::send_plans_srvRequest>
{
  static const char* value()
  {
    return DataType< ::prx_simulation::send_plans_srv >::value();
  }
  static const char* value(const ::prx_simulation::send_plans_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prx_simulation::send_plans_srvResponse> should match 
// service_traits::MD5Sum< ::prx_simulation::send_plans_srv > 
template<>
struct MD5Sum< ::prx_simulation::send_plans_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prx_simulation::send_plans_srv >::value();
  }
  static const char* value(const ::prx_simulation::send_plans_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prx_simulation::send_plans_srvResponse> should match 
// service_traits::DataType< ::prx_simulation::send_plans_srv > 
template<>
struct DataType< ::prx_simulation::send_plans_srvResponse>
{
  static const char* value()
  {
    return DataType< ::prx_simulation::send_plans_srv >::value();
  }
  static const char* value(const ::prx_simulation::send_plans_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRX_SIMULATION_MESSAGE_SEND_PLANS_SRV_H
