// Generated by gencpp from file prx_simulation/send_lqr_srvRequest.msg
// DO NOT EDIT!


#ifndef PRX_SIMULATION_MESSAGE_SEND_LQR_SRVREQUEST_H
#define PRX_SIMULATION_MESSAGE_SEND_LQR_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <prx_simulation/lqr_msg.h>

namespace prx_simulation
{
template <class ContainerAllocator>
struct send_lqr_srvRequest_
{
  typedef send_lqr_srvRequest_<ContainerAllocator> Type;

  send_lqr_srvRequest_()
    : all_lqrs()
    , system_name()  {
    }
  send_lqr_srvRequest_(const ContainerAllocator& _alloc)
    : all_lqrs(_alloc)
    , system_name(_alloc)  {
    }



   typedef std::vector< ::prx_simulation::lqr_msg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::prx_simulation::lqr_msg_<ContainerAllocator> >::other >  _all_lqrs_type;
  _all_lqrs_type all_lqrs;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _system_name_type;
  _system_name_type system_name;




  typedef boost::shared_ptr< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct send_lqr_srvRequest_

typedef ::prx_simulation::send_lqr_srvRequest_<std::allocator<void> > send_lqr_srvRequest;

typedef boost::shared_ptr< ::prx_simulation::send_lqr_srvRequest > send_lqr_srvRequestPtr;
typedef boost::shared_ptr< ::prx_simulation::send_lqr_srvRequest const> send_lqr_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_simulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'prx_simulation': ['/home/parallels/Desktop/ROS_workspace/src/prx_simulation/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3975634644201b15c64815224657220";
  }

  static const char* value(const ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3975634644201b1ULL;
  static const uint64_t static_value2 = 0x5c64815224657220ULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_simulation/send_lqr_srvRequest";
  }

  static const char* value(const ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_simulation/lqr_msg[] all_lqrs\n\
string system_name\n\
\n\
================================================================================\n\
MSG: prx_simulation/lqr_msg\n\
float64[] gain_matrix\n\
float64[] center\n\
float64[] control\n\
float64[] cost\n\
float64 radius\n\
";
  }

  static const char* value(const ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.all_lqrs);
      stream.next(m.system_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct send_lqr_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_simulation::send_lqr_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "all_lqrs[]" << std::endl;
    for (size_t i = 0; i < v.all_lqrs.size(); ++i)
    {
      s << indent << "  all_lqrs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::prx_simulation::lqr_msg_<ContainerAllocator> >::stream(s, indent + "    ", v.all_lqrs[i]);
    }
    s << indent << "system_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.system_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_SIMULATION_MESSAGE_SEND_LQR_SRVREQUEST_H
