// Generated by gencpp from file prx_simulation/set_sim_state_srv.msg
// DO NOT EDIT!


#ifndef PRX_SIMULATION_MESSAGE_SET_SIM_STATE_SRV_H
#define PRX_SIMULATION_MESSAGE_SET_SIM_STATE_SRV_H

#include <ros/service_traits.h>


#include <prx_simulation/set_sim_state_srvRequest.h>
#include <prx_simulation/set_sim_state_srvResponse.h>


namespace prx_simulation
{

struct set_sim_state_srv
{

typedef set_sim_state_srvRequest Request;
typedef set_sim_state_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_sim_state_srv
} // namespace prx_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prx_simulation::set_sim_state_srv > {
  static const char* value()
  {
    return "33a7b8b2ef07b59c7ef6feae729bf484";
  }

  static const char* value(const ::prx_simulation::set_sim_state_srv&) { return value(); }
};

template<>
struct DataType< ::prx_simulation::set_sim_state_srv > {
  static const char* value()
  {
    return "prx_simulation/set_sim_state_srv";
  }

  static const char* value(const ::prx_simulation::set_sim_state_srv&) { return value(); }
};


// service_traits::MD5Sum< ::prx_simulation::set_sim_state_srvRequest> should match 
// service_traits::MD5Sum< ::prx_simulation::set_sim_state_srv > 
template<>
struct MD5Sum< ::prx_simulation::set_sim_state_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prx_simulation::set_sim_state_srv >::value();
  }
  static const char* value(const ::prx_simulation::set_sim_state_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prx_simulation::set_sim_state_srvRequest> should match 
// service_traits::DataType< ::prx_simulation::set_sim_state_srv > 
template<>
struct DataType< ::prx_simulation::set_sim_state_srvRequest>
{
  static const char* value()
  {
    return DataType< ::prx_simulation::set_sim_state_srv >::value();
  }
  static const char* value(const ::prx_simulation::set_sim_state_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prx_simulation::set_sim_state_srvResponse> should match 
// service_traits::MD5Sum< ::prx_simulation::set_sim_state_srv > 
template<>
struct MD5Sum< ::prx_simulation::set_sim_state_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prx_simulation::set_sim_state_srv >::value();
  }
  static const char* value(const ::prx_simulation::set_sim_state_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prx_simulation::set_sim_state_srvResponse> should match 
// service_traits::DataType< ::prx_simulation::set_sim_state_srv > 
template<>
struct DataType< ::prx_simulation::set_sim_state_srvResponse>
{
  static const char* value()
  {
    return DataType< ::prx_simulation::set_sim_state_srv >::value();
  }
  static const char* value(const ::prx_simulation::set_sim_state_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRX_SIMULATION_MESSAGE_SET_SIM_STATE_SRV_H
