// Generated by gencpp from file prx_simulation/world_config_msg.msg
// DO NOT EDIT!


#ifndef PRX_SIMULATION_MESSAGE_WORLD_CONFIG_MSG_H
#define PRX_SIMULATION_MESSAGE_WORLD_CONFIG_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <prx_simulation/state_msg.h>
#include <prx_simulation/state_msg.h>

namespace prx_simulation
{
template <class ContainerAllocator>
struct world_config_msg_
{
  typedef world_config_msg_<ContainerAllocator> Type;

  world_config_msg_()
    : plant_configs()
    , obstacle_configs()
    , node_name()
    , timestamp(0.0)  {
    }
  world_config_msg_(const ContainerAllocator& _alloc)
    : plant_configs(_alloc)
    , obstacle_configs(_alloc)
    , node_name(_alloc)
    , timestamp(0.0)  {
    }



   typedef std::vector< ::prx_simulation::state_msg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::prx_simulation::state_msg_<ContainerAllocator> >::other >  _plant_configs_type;
  _plant_configs_type plant_configs;

   typedef std::vector< ::prx_simulation::state_msg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::prx_simulation::state_msg_<ContainerAllocator> >::other >  _obstacle_configs_type;
  _obstacle_configs_type obstacle_configs;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _node_name_type;
  _node_name_type node_name;

   typedef double _timestamp_type;
  _timestamp_type timestamp;




  typedef boost::shared_ptr< ::prx_simulation::world_config_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prx_simulation::world_config_msg_<ContainerAllocator> const> ConstPtr;

}; // struct world_config_msg_

typedef ::prx_simulation::world_config_msg_<std::allocator<void> > world_config_msg;

typedef boost::shared_ptr< ::prx_simulation::world_config_msg > world_config_msgPtr;
typedef boost::shared_ptr< ::prx_simulation::world_config_msg const> world_config_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prx_simulation::world_config_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prx_simulation::world_config_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace prx_simulation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'prx_simulation': ['/home/parallels/Desktop/ROS_workspace/src/prx_simulation/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::prx_simulation::world_config_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prx_simulation::world_config_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_simulation::world_config_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prx_simulation::world_config_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_simulation::world_config_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prx_simulation::world_config_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prx_simulation::world_config_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95a57da07d2f6a3f3c1e6a8109a5aa38";
  }

  static const char* value(const ::prx_simulation::world_config_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95a57da07d2f6a3fULL;
  static const uint64_t static_value2 = 0x3c1e6a8109a5aa38ULL;
};

template<class ContainerAllocator>
struct DataType< ::prx_simulation::world_config_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_simulation/world_config_msg";
  }

  static const char* value(const ::prx_simulation::world_config_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prx_simulation::world_config_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prx_simulation/state_msg[] plant_configs\n\
prx_simulation/state_msg[] obstacle_configs\n\
string node_name\n\
float64 timestamp\n\
================================================================================\n\
MSG: prx_simulation/state_msg\n\
float64[] elements\n\
string node_name\n\
string consumer_name\n\
float64 timestamp\n\
";
  }

  static const char* value(const ::prx_simulation::world_config_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prx_simulation::world_config_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plant_configs);
      stream.next(m.obstacle_configs);
      stream.next(m.node_name);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct world_config_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prx_simulation::world_config_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prx_simulation::world_config_msg_<ContainerAllocator>& v)
  {
    s << indent << "plant_configs[]" << std::endl;
    for (size_t i = 0; i < v.plant_configs.size(); ++i)
    {
      s << indent << "  plant_configs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::prx_simulation::state_msg_<ContainerAllocator> >::stream(s, indent + "    ", v.plant_configs[i]);
    }
    s << indent << "obstacle_configs[]" << std::endl;
    for (size_t i = 0; i < v.obstacle_configs.size(); ++i)
    {
      s << indent << "  obstacle_configs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::prx_simulation::state_msg_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacle_configs[i]);
    }
    s << indent << "node_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.node_name);
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRX_SIMULATION_MESSAGE_WORLD_CONFIG_MSG_H
